name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: set up GO 1.19
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make Test